name: Install frontend dependencies

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: .
        run: npm install

      - name: Create ZIP
        shell: powershell
        run: |
          Compress-Archive `
            -Path node_modules `
            -DestinationPath frontend-node_modules.zip `
            -CompressionLevel Optimal

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: frontend-node-modules
          path: frontend-node_modules.zip
          retention-days: 1
